services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped

  rag:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - DOCKER_BUILDKIT=1
    volumes:
      - ../src:/app/src
      - ../tests:/app/tests
    depends_on:
      - qdrant

volumes:
  qdrant_storage:
    driver: local
