services:
  rag-app:
    container_name: rag-app
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
    depends_on:
      - qdrant

  qdrant:
    container_name: qdrant
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ../qdrant_storage:/qdrant/storage
    restart: unless-stopped

volumes:
  qdrant_storage:
    driver: local
