services:
  rag-app:
    container_name: rag-app
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ..:/app
    depends_on:
      - qdrant
      - ollama
    networks:
      - rag-network
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: >
      sh -c '
      echo "Waiting for Ollama to initialize..." &&
      while ! curl -s http://ollama:11434/api/tags >/dev/null; do
        sleep 1
      done &&
      echo "Ollama is ready!" &&
      ollama pull orca-mini &&
      streamlit run src/app.py --server.address=0.0.0.0 --server.port=8501'
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://ollama:11434/api/tags"]
      interval: 10s
      timeout: 5s
      retries: 5

  qdrant:
    container_name: qdrant
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ../qdrant_storage:/qdrant/storage
    restart: unless-stopped
    networks:
      - rag-network

  ollama:
    container_name: ollama
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - rag-network
    deploy:
      resources:
        reservations:
          memory: 2GB

volumes:
  qdrant_storage:
    driver: local
  ollama_data:
    driver: local

networks:
  rag-network:
    driver: bridge
