services:
  rag-app:
    container_name: rag-app
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
    depends_on:
      - qdrant
      - ollama
    networks:
      - rag-network
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: >
      sh -c '
      echo "Waiting 3 minutes for Ollama to initialize..." &&
      for i in {180..1}; do
        echo -ne "\rStarting in $$i seconds...   \r";
        sleep 1;
      done &&
      python -m src.main --interactive'
    stdin_open: true
    tty: true

  qdrant:
    container_name: qdrant
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ../qdrant_storage:/qdrant/storage
    restart: unless-stopped
    networks:
      - rag-network

  ollama:
    container_name: ollama
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - rag-network
    deploy:
      resources:
        reservations:
          memory: 2GB

volumes:
  qdrant_storage:
    driver: local
  ollama_data:
    driver: local

networks:
  rag-network:
    driver: bridge
